name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Pull WordPress image from Docker Hub
      run: docker pull wordpress:latest
      
    - name: Run software composition analysis
      run: |
        docker run --rm -v "$(pwd):/src" -w /src 
        aquasec/trivy:latest wordpress:latest
        
    - name: Deploy Terraform infrastructure
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0
      env:
        TF_VAR_region: eu-central-1
        
    - name: Terraform init
      run: terraform init
      
    - name: Terraform plan
      run: terraform plan -out=tfplan
      
    - name: Terraform apply
      run: terraform apply -auto-approve tfplan

