name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Retrieve WordPress image from Docker Hub
        run: docker pull wordpress:latest

      - name: Run software composition analysis
        uses: docker://aquasec/trivy:latest
        with:
          args: wordpress:latest

      - name: Deploy Terraform infrastructure
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
        env:
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_region: eu-central-1
        run: |
          terraform init
          terraform plan -out=tfplan
          terraform apply tfplan
